spring:
  kafka:
    bootstrap-servers: 172.22.167.76:9092
    consumer:
      bootstrap-servers: 172.22.167.76:9092
      auto-offset-reset: earliest
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      bootstrap-servers: 172.22.167.76:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
